class CfgWorlds
{
    class GenericNames
    {
        class CzechMen
        {
            class FirstNames
            {
                petr = "Petr";
                david = "David";
                roman = "Roman";
                ivan = "Ivan";
                jan = "Jan";
                honza = "Honza";
                jenda = "Jenda";
                adam = "Adam";
                bohuslav = "Bohuslav";
                borek = "Borek";
                boris = "Boris";
                cecil = "Cecil";
                cyril = "Cyril";
                daniel = "Daniel";
                dalibor = "Dalibor";
                dan = "Dan";
                denis = "Denis";
                tom = "Tom";
                emil = "Emil";
                erik = "Erik";
                felix = "Felix";
                jakub = "Jakub";
                ladislav = "Ladislav";
                lubor = "Lubor";
                michael = "Michael";
                michal = "Michal";
                milan = "Milan";
                miroslav = "Miroslav";
                mirek = "Mirek";
                oskar = "Oskar";
                oliver = "Oliver";
                osvald = "Osvald";
                otakar = "Otakar";
                pavel = "Pavel";
                patrik = "Patrik";
                prokop = "Prokop";
                radek = "Radek";
                karel = "Karel";
                martin = "Martin";
                vojta = "Vojta";
                hugo = "Hugo";
                josef = "Josef";
                lukas = "Lukas";
                bolek = "Bolek";
                standa = "Standa";
                filip = "Filip";
                libor = "Libor";
                richard = "Richard";
                igor = "Igor";
                adolf = "Adolf";
                gustav = "Gustav";
                bohdan = "Bohdan";
                dubroslav = "Dubroslav";
                silvestr = "Silvestr";
                hynek = "Hynek";
                sasha = "Sasha";
            };
            class LastNames
            {
                soukup = "Soukup";
                svoboda = "Svoboda";
                zeman = "Zeman";
                marek = "Marek";
                david = "David";
                urban = "Urban";
                valenta = "Valenta";
                vacek = "Vacek";
                stejskal = "Stejskal";
                kraus = "Kraus";
                klaus = "Klaus";
                straka = "Straka";
                kohout = "Kohout";
                vlk = "Vlk";
                adamec = "Adamec";
                zelenka = "Zelenka";
                macek = "Macek";
                brabec = "Brabec";
                linhart = "Linhart";
                mozek = "Mozek";
                koudelka = "Koudelka";
                kouba = "Kouba";
                smetana = "Smetana";
                kvapil = "Kvapil";
                hoffmann = "Hofman";
                Dohnal = "Dohnal";
                trnka = "Trnka";
                sobotka = "Sobotka";
                musil = "Musil";
                martin = "Martin";
                michal = "Michal";
                daniel = "Daniel";
                satan = "Satan";
                turek = "Turek";
                back = "Back";
                havel = "Havel";
                malarkey = "Malarkey";
                janda = "Janda";
                strana = "Strana";
                beran = "Beran";
                nosek = "Nosek";
                vrba = "Vrba";
                sochor = "Sochor";
            };
        };
    };
};